spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cleanwater
    username: root
    password: qwer1234
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 5
      idleTimeout: 600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: root
    password: qwer1234